version: '3.8'

services:
  postgresql:
    hostname: "localhost"
    image: postgres:latest
    container_name: MarketGuru
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-marketguru}
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}